Feature/4
dev-floor/untitled-client pull request #15
Opened 2021-04-16 13:28 UTC by dayonxxi

**작업한 내용**
- 게시물 상세 조회 페이지 바디 컴포넌트 개발
- 전체를 main 태그로 감싸고, article 태그 안에 본문내용과 첨부된 이미지 볼 수 있도록
- "article-descriptions" div 태그 안에는 해시태그 버튼과, 좋아요 등의 버튼이 들어가도록
- (좋아요수 구현 부분은 counter로 구현하려했으나 버튼 3개의 값이 모두 똑같이 올라가버려서 3개의 버튼이 따로 count될 수 있도록 수정봐야 할 것 같습니다.)

2021-04-17 07:05 UTC, Derek-94 requested changes
@dayonxxi 님! 첫번째 PR 코드 잘 봤습니다 :)

고생하셨어요! 👍

다만 코드 리뷰에 남기긴 했지만 몇가지 놓치신거 다시 한번 말씀드릴게욤.
1. 코드 중복
 - 안쓰는 변수나, 똑같은 내용이 약간 있는 것 같아요. PR 날리기 전에 한번 주르륵 훑어보시고 날리는게 좋지않을까! 생각이듭니다.
2. 함수형으로 개발.
 - `React` 컴포넌트를 클래스형이 아닌 함수형으로 개발하시는게 나중에 더 좋을 것 같습니다 :)

그 외에 필요한 사항들은 코드 단위로 확인 부탁드려요!

고생하셨습니다. 😀

2021-04-17 07:05 UTC, Derek-94 commented on src/Article/presentational/ArticleBody.tsx
> +import React, { useState } from "react";
`useState` 라는 hook이 하단에 쓰인 적이 없는 것으로 보여요. 

이 친구를 넣은 이유가 궁금합니다아!

2021-04-17 07:05 UTC, Derek-94 commented on src/Article/presentational/ArticleBody.tsx
> +}
이 두 친구는 어떤 역할을 하는 친군가요..?!
음 하단에 쓰인적이 없는것 같아요. 

혹시 쓰인다고 해도, 저희 `interface` 는 한곳에 모아두기로 했었죠! 참고 부탁드려용 :)

2021-04-17 07:05 UTC, Derek-94 commented on src/Article/presentational/ArticleBody.tsx
> +    }
호곡.. 클래스도 좋긴하지만 함수형으로 `react` 를 다루는 것이 좋을 것 같아요. 

1. 나중에 나온 기능으로, 더 손쉽게 핸들링이 가능해요.
2. react hooks 로 life cycle 을 조정할 수 있어요.
3. 이벤트를 바인딩 해줄때, `this` 를 쓰지 않아도 돼요.

등등.. 현주님도 이미 함수형으로 개발을 하셨기 때문에, 함수형이 더 좋지 않을까 생각이 듭니다. 

함수형으로 쓴다면, 여기에 `contructor` 도 상단에 쓰신 `useState` 로 대체가 가능하구요!

2021-04-17 07:05 UTC, Derek-94 commented on src/Article/css/ArticleBody.css
> +}
쓰이지 않는 친구들은 일단 삭제하는 것이 좋지 않을까요?!

2021-04-17 07:05 UTC, Derek-94 commented on src/Article/presentational/ArticleBody.tsx
> +}
이 친구가.. 보니까 하단에 이 `article` 변수를 렌더링 하더라구요?

뭐 그럴수도 있지만! 저희는 `api` 통신으로 받은 데이터, 즉 여기서는 임시적으로 `dummyData`에 들어있는 
정보를 렌더링해야해요! 하단에 48번째 줄부터 자세한 설명 추가해놓겠습니당!

2021-04-17 07:05 UTC, Derek-94 commented on src/Article/presentational/ArticleBody.tsx
> +                </section>
굳굳! 너무 좋았어요. 이렇게 `ArticleBody` 는 렌더링**만** 담당하는 친구죠! 

그러니까, `ArticleBody`는 데이터를 받아요. 누군가가(container랍니당), 

"야, 이거 줄테니까 넌 이거 받고 그리기만 해라!"

라고 해서 그 역할을 수행하는 거고, 여기서 누군가가 주는 `이거` 는 `ArticleBody` 가 인자로 받는 `dummyData` 랍니다.
심지어 밑에 destructing도 잘하셨어요! `spread` 를 써서 잘 뿌려줬으니, 그 받은 데이터를 뿌리기만 하면 되겠죠?

```suggestion
const ArticleBody = ( dummyData: ArticleDetailApi ) => {
    const {content, author, hashtags, favorites, wonders, clips} = {...dummyData}
    
    return(
        <main>
            <article>
                <section className = "article-content">
                    <h6>{content}</h6>
                </section>
                <section className = "article-image">
                    <img src={author.image} alt='첨부된 이미지 파일'/>
                </section>
```

이렇게요! 

이렇다면 `ArticleBody` 가 받은 `dummyData` 를 똑바로 쓰는 것으로 볼 수 있을 것 같아요.

위에 5번째 줄에 `article` 로 선언하면 그 정보만!을 렌더링하니까.. 재사용이 심각하게 떨어지는 부분이랍니다 ㅜㅜ

2021-04-17 07:05 UTC, Derek-94 commented on src/Article/presentational/ArticleBody.tsx
> +    );
- 별건 아니지만 꼭 들여쓰기 컨벤션 지켜주세용! 😀

- 그리고 음 그 `count` 라는 변수가 늘어나면, 늘어난 값을 보여줘야 할 것 같은데, 그 부분은 어디있는지 궁금해요.
내부적으로 늘리기만 하고 안보여주는 것 아닐까 생각이들어요!

- 그리고 사용자가 `좋아요` , `나도 궁금해요` , `스크랩` 버튼을 누르고, 또 다시 누르면 취소를 하는 로직도 필요할 것 같아요. 저희 인스타 사용할때 좋아요 잘못누르면 다시 눌러서 하트 없애는 것 처럼요. 
그 부분은 `toggle` 기능을 구현해야할 것 같은데, 어떻게 생각 하시는지 궁금하네요 🤔 `onDecrement` 라는 함수를 만드신것 보아하니 그 기능을 생각하신 것 같긴해욥.
저도 지금 생각해보니 좀 어려울 것 같은 느낌이.. 😂

그냥 생각나는 대로 적어보자면, 이 버튼에 대한 이벤트 핸들링 함수는 각자 필요할 것 같은 느낌이 들어요.

추후에 `api` 랑 엮이면 각자 request를 날릴것 같긴 하거든요. 또한 그렇게 하면 적어 주신 문제점인 **한 번에 다 같이 증가된다**는 문제도 해결 되지 않을까 하는 느낌..? 입니다!

2021-04-17 07:05 UTC, Derek-94 commented on src/Article/css/ArticleBody.css
> +    display: flex;
두둥.. 중복되었어요..!

2021-04-17 07:05 UTC, Derek-94 commented on src/Article/presentational/ArticleBody.tsx
> +                    <CounterButton/>
이 3개의 컴포넌트는 하트 / 좋아요 / 스크랩 인것 같은데요!

각자 다 따로 구현이 되어야 하지않을까요?

2021-04-17 11:25 UTC, hyunju95 reviewed
석기님이 너무 꼼꼼히 리뷰를 해주셔서 잘 참고 해주시면 좋을 것 같네요!

PR 올리기 전에 코드를 한번 점검 하시면서 안쓰는 변수, 함수 삭제 / 들여쓰기등의 가독성에 영향을 미치는 요소들을 다시 한번 점검해주시면 리뷰하기에 더 좋을 거 같습니다!

개발하느라 수고하셨습니다~!

2021-04-17 11:25 UTC, hyunju95 commented on src/Article/css/ArticleBody.css
> +}
내용이 없는 부분은 나중에 헷갈릴 수 있으니 삭제 부탁 드려요~!

2021-05-02 03:19 UTC, hyunju95 approved these changes
Approve

2021-05-02 03:19 UTC, Derek-94 approved these changes
`ArticleBodyContainer` 부분에서 `API` 콜하는 부분으로 약간 고치면 될 것 같기는 해요!

일단은 approve 하고나서 그 부분은 수정하겠습니다.

2021-05-02 03:24 UTC, merged