feature(게시물 상세 조회): 게시물 삭제 기능 구현
dev-floor/untitled-client pull request #46
Opened 2021-05-23 00:32 UTC by dayonxxi

### **상세 내용**

- 게시물 삭제 기능 구현
   - 삭제 버튼을 눌렀을 때 '예'를 누르면 삭제 된후 게시물 목록 화면으로 넘어감
   - '아니오'를 누르면 해당 게시물에 그대로 있음

closes #41

2021-05-25 05:22 UTC, Derek-94 requested changes
고생하셨습니다! 

저번 회의 내용 참고하셔서 조금만 손보시면 될것 같아요~!

2021-05-25 05:22 UTC, Derek-94 commented on src/Article/container/ArticleHeaderContainer.tsx
> +      return window.location.assign("/articleList");
저번에 말씀드린것 && 오늘 질문 주신내용 바탕으로 한번 `history` 사용해서 수정하시면 될것 같습니다~

2021-05-25 05:22 UTC, Derek-94 commented on src/Article/container/ArticleHeaderContainer.tsx
> +    return window.location.reload(true);
얘도 굳이 새로고침 할 필요가 없고, 가만히 있음 되는거니까, 그 부분 생각해서 수정하셔도 될것같아요!

2021-05-30 04:45 UTC, hyunju95 approved these changes

2021-06-01 08:38 UTC, Derek-94 approved these changes
고생많으셨습니다~

저번보다 뭔가 더 간결해진 느낌? 이네요.

import 순서랑 뭐 띄어쓰기? 관련해서 엔터 몇번만 치시고 머지부탁드립니당

2021-06-01 08:38 UTC, Derek-94 commented on src/Article/presentational/ArticleHeader.tsx
>  import { ArticleHeaderProps } from '../argumentsPropsInterface/ArticleProps';
그 현주가 언급한 부분 `import 순서 관련 컨벤션` 적용해야하지 않을까 싶네요..!

[여기](https://www.notion.so/lxxjn0/3015224318ca4dd3aa37e0135f89b740?p=68aa666db83140cbaf59fa56b0f8859c) 확인부탁드려요!

2021-06-02 13:54 UTC, merged