feature(게시물 상세 조회): 댓글 컴포넌트 수정/삭제
dev-floor/untitled-client pull request #47
Opened 2021-05-23 04:31 UTC by hyunju95

댓글 컴포넌트에 수정/삭제 버튼 추가 및 click Handler 추가
컴포넌트 전달 props에 핸들러 추가하여 수정
댓글 수정 기능 구현
댓글 삭제 기능 구현

closes #45

2021-05-25 05:17 UTC, Derek-94 requested changes
코드리뷰 했습니다!

저번에 오프라인으로 설명해주신 내용 생각하면서 리뷰했습니다.

전제척으로 디버깅용 콘솔 출력 코드가 많은데, 사실 이건 그냥 냅둬도 될것 같기도하고 그런데.. 어떻게 생각하시는지 궁금합니다.

자세한 내용 코드단에 리뷰했어요.

정말 고생많았습니다~

2021-05-25 05:17 UTC, Derek-94 commented on src/App.tsx
> -import React, { Fragment, useState } from 'react';
엥 이거 `Fragment` 가 뭐죠..? 처음보네요

2021-05-25 05:17 UTC, Derek-94 commented on src/Article/argumentsPropsInterface/ArticleProps.tsx
> +  onRegisterDeleteComment: (deleteId: number) => void;
이거 관련해서요,

함수들 네이밍이랑, `apiProps` 나 여기 파일에 있는 `props` 들 네이밍 한번 만나서 다 정리할 필요가 있을것 같네요.

2021-05-25 05:17 UTC, Derek-94 commented on src/Article/container/CommentContainer.tsx
> +      commentList.map((comment, index) =>
여기 `index` 는 쓰이지 않는데, 들어간 이유가 궁금해욤.

2021-05-25 05:17 UTC, Derek-94 commented on src/Article/presentational/ArticleHeader.tsx
> +        {options.map((op, index) => (
읭 얘도 `map` 함수내부에 인덱싱 변수가 추가됬네요!

2021-05-25 05:17 UTC, Derek-94 commented on src/Article/presentational/CommentArea.tsx
> +});
5/23에 회의한 내용처럼, 이 `atom` 들도 어디론가 한곳에 모여있으면 좋겠네요. 이거를.. 어디다가 둘까요?

src/ 내부에 `api`, `Article`, ... 얘들있는 곳에 두는것은 어떤지..? 여기 있는 `data` 폴더는 더미데이터니까 어쨌든 언젠가
없어질 애니깐요.

2021-05-25 05:17 UTC, Derek-94 commented on src/ArticleList/presentational/ArticleList.tsx
> +        {options.map((op, index) => (
이 부분두요! 혹시 일부러 추가하신건지 / eslint 나 prettier 가 추가한건 지 궁금하네요

2021-05-25 05:17 UTC, Derek-94 commented on src/Article/presentational/CommentArea.tsx
> +  const deleteCommentId = useRecoilValue(DeleteCommentId);
이거 저번에 말씀드린것 처럼 간단하게 수정 가능!

[여기](https://taegon.kim/archives/10105)에 `useRecoilState` 함수 참고 부탁합니다 ㅎㅎ

2021-05-25 05:17 UTC, Derek-94 commented on src/Article/presentational/CommentArea.tsx
> +    console.log(`${newComment.id}번째 댓글을 추가`);
디버깅용 콘솔은 약간 지워도 될듯..하지않을까요?!

2021-05-25 05:17 UTC, Derek-94 commented on src/Article/presentational/CommentArea.tsx
> +  onRegisterUpdateComment,
보니까 이 `onRegisterUpdateComment` 이라는 친구는 container -> CommentArea -> Comment 까지 해서 쭈루룩 해서 계속 Props로 받는 구조인 것 같은데, 맞나요?

맞다면.. 얘를 그냥 먼가 `selector` 함수로 만들어서 `recoil` 로 관리해도 될 것 같은 느낌이에요.

2021-05-25 05:17 UTC, Derek-94 commented on src/Article/presentational/CommentArea.tsx
> +      )}
아 이제 보니까 좀 알것같기도하네요.

1. 사용자가 수정하고 싶은 댓글을 누른다.
2. `recoil` 변수가 바뀐다
3. 거기에 묶여있는것이 여기 삼항연산자 연산이니까, 수행된다

약간 이런 느낌인것 같네요.

2021-05-29 11:22 UTC, hyunju95 commented on src/Article/container/CommentContainer.tsx
> +      commentList.map((comment, index) =>
이거 console log에 key관련한 오류 찍히는 부분에 대해서 보통 지정안된 상태에서는 map에서 기본 제공되는 index로 key를 사용한다고 해서 수정해보려고 추가 했다가 까먹고 수정 안했던 부분이예요!

2021-05-29 11:22 UTC, hyunju95 commented on src/Article/presentational/ArticleHeader.tsx
> +        {options.map((op, index) => (
위에 내용과 동일합니다

2021-05-29 11:22 UTC, hyunju95 commented on src/Article/presentational/CommentArea.tsx
> +});
네네 요부분은 요번회의때 전반적으로 디렉토리 구조및 변수 한 번 정리할 필요가 있겠네요!!

2021-05-29 11:22 UTC, hyunju95 commented on src/Article/presentational/CommentArea.tsx
> +  onRegisterUpdateComment,
네 구조는 맞습니다. selector함수 정확한 사용법을 잘 몰라서 좀 찾아 봐야 할 것 같네요! 근데 만약 selector로 관리한다면 registerUpdate말고도 다른 함수들(Delete/Create)도 모두 selector로 관리할 수 있는 구조인가요? 다른 핸들러도 전달받는건 동일한 구조인것 같은데

2021-05-29 11:22 UTC, hyunju95 commented on src/Article/presentational/CommentArea.tsx
> +  const deleteCommentId = useRecoilValue(DeleteCommentId);
넵 이부분 반영하도록 하겠습니다!

2021-05-29 11:22 UTC, hyunju95 commented on src/Article/presentational/CommentArea.tsx
> +    console.log(`${newComment.id}번째 댓글을 추가`);
요거는 해당 부분이 완벽하게 구현 될 때까지 계속 참고할 부분인 것 같아서 크게 거슬리지 않는다면 남겨 놓는 게 좋을 것 같아요!

2021-05-29 11:22 UTC, hyunju95 commented on src/ArticleList/presentational/ArticleList.tsx
> +        {options.map((op, index) => (
위에 내용과 동일합니다!

2021-05-29 11:22 UTC, hyunju95 commented on src/App.tsx
> -import React, { Fragment, useState } from 'react';
어 요건 Modal 개발할 때 도입했다가 결국 사용안한 기능인데 코드에 추가되어있길래 이번에 제거한 부분입니다~!

2021-05-30 05:27 UTC, dayonxxi approved these changes

2021-05-30 05:27 UTC, dayonxxi commented on src/Article/argumentsPropsInterface/ArticleProps.tsx
> +  onRegisterUpdateComment: (newComment: ArticleCommentApi) => void;
요건 CommentAreaProps에도 존재하고 CommentProps에도 존재하는건가요?! 뭔가 이유가 있어서 설명해주셨던 것 같은데 기억이 안나네욤,,

2021-05-30 05:27 UTC, Derek-94 approved these changes

2021-05-30 06:08 UTC, merged