feature(게시판 목록 조회): 사이드바 구현
dev-floor/untitled-client pull request #53
Opened 2021-06-06 03:39 UTC by dayonxxi

여긴 회의 마치고 다시 작성할게욤

2021-06-08 12:07 UTC, Derek-94 requested changes
까먹고 있다가 이제 리뷰 남깁니다! 사이드바 꼭꼭 이번주에는 마무리해보자구요~

2021-06-08 12:07 UTC, Derek-94 commented on src/Board/container/BoardDetailContainer.tsx
> +  const sideBarData = sidebarAPI.get();
다연님 이거 `api` 콜 이렇게 하면 아마 비동기적으로 안될것 같아요!

저번에 준영님께서 `temp` 브랜치 따서 `api` 싹 해주셨던거 있었는데, 그 방법으로 `api` 콜 수정해야 할 것 같습니다!

위 12번째 줄, 23번째 줄, 28번째줄 처럼 
`useState` 로 관리 -> loadData 안에서 `api` 콜 하고 `set` 하기 -> 그 `loadData` 를 `useEffect` 로 관리

이렇게 들어가야할 것 같아요.

2021-06-11 10:03 UTC, dayonxxi commented on src/Board/container/BoardDetailContainer.tsx
> +  const sideBarData = sidebarAPI.get();
말씀주신대로 수정하겠습니다!

2021-06-12 11:11 UTC, hyunju95 reviewed
수고하셨습니당~!

2021-06-12 11:11 UTC, hyunju95 commented on src/api/api.ts
> +};
EOL 처리가 빠졌네용!

2021-06-12 11:11 UTC, hyunju95 commented on src/data/SideBarDummyData.ts
> +export default sidebarDummyData;
요거 back쪽에서 변경된거 api 명세 알려주시면 바꿔서 다시 테스트하시면 될것같아요!

2021-06-12 13:01 UTC, Derek-94 approved these changes
`api` 수정부분 확인했습니다~

2021-06-12 13:01 UTC, Derek-94 commented on src/Board/container/BoardDetailContainer.tsx
> +  const sideBarData = sidebarAPI.get();
오홋! 확인했습니다! 정확히 잘 구현하셨어요!

2021-06-25 03:49 UTC, Derek-94 requested changes
고생하셨어요. 

수정해야할 것이 좀 있어서 request 날렸습니다. 

죄송하지만 오늘안에 해주셔야 할것같아요. 저도 시간이 없네요ㅜ

2021-06-25 03:49 UTC, Derek-94 commented on src/App.tsx
> +  const sideBarData = sidebarAPI.get();
다연님.

이거 저번에... 말씀드린것 같고, 다연님께서도 이거 반영해서 수정하셨었어요!

그냥 이렇게 `API` 통신하면 비동기적으로 통신이 아마 안되어서 수정했던거 기억하실까요?

2021-06-25 03:49 UTC, Derek-94 commented on src/App.tsx
> +  const [sidebar, setSidebar] = useState(false);
`state` 관련 변수 이름 더 가독성 좋게 수정 부탁드려요. 

`사이드바를 보여줄지 말지` 정도의 정보니까, `[showSidebar, setShowSidebar]` 이나 `[showSidebar, setShowSidebar]` 

정도가 좋을것 같네요. 

단순히 그냥 `sidebar` 라고만 한다면 팀원입장에서 얘가 뭐하는건지 한번에 와닿지가 않아요.

2021-06-25 03:49 UTC, Derek-94 commented on src/ArticleList/container/ArticleListContainer.tsx
> +
이거 제가 구현한건데 여기 새롭게 추가되었다고 뜨는건지 궁금하네요...?

2021-06-25 03:49 UTC, Derek-94 commented on src/Router.tsx
> -      <hr />
예전부터 지우고 싶었는데 다연님 덕분에 드디어 사이드바가 구현되었네욤

2021-06-25 03:49 UTC, Derek-94 commented on src/Commons/Sidebar.tsx
> +      </nav>
이 부분 관련해서 음 생각이 좀 많은데요,

1. `수업게시판` , `질문게시판` 이렇게 37번째 줄, 46번째 줄에 박아두면 나중에 일일히 고쳐야하지 않을까요?

 - `sideBarData` 데이터 안에 게시판 이름이 있을텐데, 그친구로 바꾸는게 좋을것 같은데, 의견 부탁드려요.

2. 만약 게시판의 종류가 많아지면, 일일히 추가해야함.

 - 말그대로입니다. 게시판이 추가되면, 다시 이부분을 수정 개발 해야 할 것 같아요.
 
 - 제가 예전에 말씀드린것 처럼, `sideBarData` 에서 `board.type.id` 의 값이 변함에 따라 사이드바 카테고리가 바뀌는것이 더 이상적인 개발이 될 것 같아요.

 - 즉, 저 친구를 렌더링할때,  `sideBarData` 의 `board.type.id` 값을 체크해서, `COURSE_BOARD` 인지, `QUESTION_BOARD` 인지, 구인 구직 게시판 값도 새롭게 추가되어 그 값에 따라 각자 배열을 만들어서 렌더링하면 좋을 것 같다, 생각이 들어요.

 - 뭔가.. 이 부분은 의견을 한번 모아보고싶네요. 다연님, 현주님 의견 부탁드려요.

2021-06-25 09:45 UTC, dayonxxi commented on src/App.tsx
> +  const sideBarData = sidebarAPI.get();
앗 그러네요..BoardDetailContainer에서 Sidebar와 App으로 내용을 옮기면서 저 수정했던 부분을 다시 생각못하고 넘어간 것 같아요
저번에 수정해봤던 부분이니 다시 수정하도록 하겠습니다!

2021-06-25 09:50 UTC, dayonxxi commented on src/App.tsx
> +  const [sidebar, setSidebar] = useState(false);
음..onClick에 전달해줄 이름을 showSidebar로 하기 위해서 state부분은 sidebar와 setSidebar로 정했던것입니다.
만약 [showSidebar, setShowSidebar] 로 한다면 onClick은 어떤 이름으로 전달해주는 것이 좋을지 고민이 되네요.. 혹시 이부분에 대해서는 어떻게 생각하시는지 궁금합니다!

2021-06-25 09:51 UTC, dayonxxi commented on src/ArticleList/container/ArticleListContainer.tsx
> +
혹시 이부분은 슬랙에서 답변드린 내용으로 해결되셨을까요??

2021-06-25 10:46 UTC, dayonxxi commented on src/Commons/Sidebar.tsx
> +      </nav>
맞아요 저도 저저번 회의때부터 이부분이 제일 고민이 많았어요. 일단 하나씩 설명드리자면

1. 나중에 새로운 게시판이 생길때마다 고쳐야한다는 문제가 있는 것은 맞습니다. 

- 우선 그냥 map을 돌며 {board.title}로 게시판이름을 출력하게 되면 이름이 여러번 표시되기 때문에 딱 한 번만 출력될 수 있도록 하기 위해서는 데이터를 따로 가공해야했습니다. 

- `new Set` 이나 `new Map`을 활용하여 게시판의 이름만 중복 없이 저장하는 배열을 만드는 것은 성공했습니다. 

- 그리고 {board.type.id}와 {board.type.title}이 있는 배열을 새로 만들어 submenu로 들어가 map을 돌며 출력될 수 있도록 시도해봤는데 {board.title} 과 {board.type.id}는 서로 연관이 없다는 점 때문에 이것저것 정말 많이 시도해보았는데 어려움이 있었습니다.

- 그래서 지난 회의 때 게시판의 개수가 많지 않기에 이렇게 구현했다고 설명드렸을 때 다른 팀원분들께서 따로 질문을 주시지 않아서 괜찮다고 생각했습니다..! 

2. 이 문제를 해결하기 위해 이중으로 map을 돌아야하는데 여러 방법 시도해봐도 typescript오류가 생겨 이중 map사용이 안되더라구요. 

 

2주간 제일 많이 고민했던 부분이기도 하고, 저도 원래는 석기님 말씀대로 구현하려고 시도했었기 때문에 설명하고 싶은 부분이 많은데 뭔가 말이 아닌 글로 설명하려니 어렵네요.. :( 이해가 되셨을진 모르겠지만 지금 글을 작성하면서 새로 떠오른 방법이 있어 다시 수정해보도록 하겠습니다

2021-06-25 11:16 UTC, Derek-94 commented on src/App.tsx
> +  const sideBarData = sidebarAPI.get();
네엡 `useEffect` 랑 `loadData` 함수 기억나시죠! 그걸로 구현하시면 됩니다.

2021-06-25 11:23 UTC, Derek-94 reviewed
대댓글 남겨놨습니다!

2021-06-25 11:23 UTC, Derek-94 commented on src/App.tsx
> +  const sideBarData = sidebarAPI.get();
네엡 `useEffect` 랑 `loadData` 함수 기억나시죠! 그걸로 구현하시면 됩니다.

2021-06-25 11:23 UTC, Derek-94 commented on src/App.tsx
> +  const [sidebar, setSidebar] = useState(false);
`onClick` 에 바인딩되어 있는 함수는 `toggleSidebar` 정도가 좋지않을까요? 클릭하면 보일지 말지이니깐요!

2021-06-25 11:23 UTC, Derek-94 commented on src/ArticleList/container/ArticleListContainer.tsx
> +
앗 넵넵 이게 올라갔네요! 죄송합니다.

2021-06-25 11:23 UTC, Derek-94 commented on src/Commons/Sidebar.tsx
> +      </nav>
사실 저도 이거 리뷰적으면서 음.. 그냥 게시판은 나중에 픽스되서 정해지니까 상관없지 않으려나, 생각도 들었구요

이게 배열을 따로 저장한다.. 마땅한 자료구조가 저도 생각이 빡! 나진 않더라구요.

이상적인 개발과 현실적인 개발은 갭이 있을 수도 있겠지만, 한번 생각나신거 너무 좋으니까 해보시고, **에바다 싶으면 그냥 이대로 두어도 될 것 같아요!!**

뭔가 딕셔너리지만, 하나의 `key` 에 여러가지 `value` 가 저장될 수 있는 자료구조가 있으면 딱이긴한데, 저도 잘 생각나진 않네요! @hyunju95 현주님께서 혹시 아시는게 있나 궁금합니다! 의견 공유해봐요

2021-06-25 11:49 UTC, hyunju95 commented on src/App.tsx
> +  const [sidebar, setSidebar] = useState(false);
변수명으로 sideBarShowState는 어떨까요?
Show 상태를 t/f로 나타내는변수니까 state를 붙여서 구분해줘도 좋을거같아요!

2021-06-25 12:00 UTC, hyunju95 reviewed
리뷰 남겼습니다 수고하셨어요!!

2021-06-25 12:00 UTC, hyunju95 commented on src/Article/container/ArticleDetailContainer.tsx
> +import FloatingButton from '../../Commons/FloatingButton';
여기 commons 디렉토리도 alias 적용해놓은거 있어서 commons/flatingbutton으로 변경해주세요!!

2021-06-25 12:00 UTC, hyunju95 commented on src/Commons/Sidebar.tsx
> +      </nav>
하나의 key에 여러value가 저장되는 구조면 multiHash를 사용하면 좋을것같은데 typescript에서 멀티해시 어떻게 사용하는지 찾아보면 좋을거같네요!  저도 이부분 좀 찾아볼게요!

2021-06-25 12:00 UTC, hyunju95 commented on src/css/TglBtn.css
> +.side-bar.active {
다연님 토글버튼 css에 사이드바관련 css가 있는건 맞지않는거같아요!
Side바관련 css를 따로만드시는게 좋을것같아요!!

2021-06-25 12:05 UTC, Derek-94 commented on src/Commons/Sidebar.tsx
> +      </nav>
멀티 해쉬라.. 일단 구글링해도 잘 안나오는 구조긴하네요 😥

2021-06-25 12:14 UTC, dayonxxi commented on src/css/TglBtn.css
> +.side-bar.active {
그렇네요..!
Sidebar.css 로 따로 뺀 후에 App.tsx에서 import하는 것으로 변경하겠습니다!!

2021-06-25 12:15 UTC, dayonxxi commented on src/Article/container/ArticleDetailContainer.tsx
> +import FloatingButton from '../../Commons/FloatingButton';
넵 알겠습니다!

2021-06-25 22:21 UTC, dayonxxi commented on src/App.tsx
> +  const [sidebar, setSidebar] = useState(false);
반영했습니다!

2021-06-26 05:14 UTC, Derek-94 approved these changes

2021-06-26 05:28 UTC, hyunju95 approved these changes
수정하신 부분 확인했습니다 수고하셨어요!

2021-06-26 05:44 UTC, merged