feat(environment): 초기 개발 환경 설정 개발
dev-floor/untitled-client pull request #6
Opened 2021-04-07 11:22 UTC by Derek-94

### 작업 내용

- 초기 개발 환경 설정 개발.
    - `create-react-app` 을 활용해 개발 환경 설정.
    - `--template typescript` 를 통해 `typescript` 템플릿으로 설정.
- `vscode` 의 Extension에서 `eslint`, `prettier` 를 install 해야 적용 가능.

closes #1

2021-04-07 12:37 UTC, lxxjn0 requested changes
초기 개발 환경 설정하는게 쉽지 않은데 작업한다고 수고했어!! 👍🏼 
그냥 간단한 요구사항? 정도만 달아뒀는데 이것만 참고해서 반영해주면 좋을 것 같어!! :)

2021-04-07 12:37 UTC, lxxjn0 commented on hongik-ce-board-fe/.eslintignore
> +build/*
디렉토리 구조가

```
untitled-client
ㄴ README.md
ㄴ hongik-ce-board-fe
  ㄴ ...
```

이런 구조로 되어있는데 hongik-ce-board-fe 전체를 최상위 폴더로 옮기면 좋을 것 같아요!

```
untitled-client
ㄴ README.md
ㄴ ...
ㄴ public
ㄴ src
ㄴ ...
```

이런 식으로요! repo를 프론트, 백 나눠서 생성했기 때문에 이렇게 최상위로 두는게 작업하기도 더 편할 것 같아요!

2021-04-07 12:37 UTC, lxxjn0 commented on hongik-ce-board-fe/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
```
# vscode
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace

# WebStorm
.idea

# Gradle
*.iml
*.ipr

# CMake
cmake-build-*/

# File-based project format
*.iws

# IntelliJ
out/

# mpeltonen/sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Crashlytics plugin (for Android Studio and IntelliJ)
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties
```

gitignore에 추가해주실 수 있을까요? vscode, webstorm 환경에 대한 예외 경로입니다.
(제가 가끔 접속해볼때 webstorm을 사용할 것 같아서요...)

2021-04-07 13:58 UTC, Derek-94 commented on hongik-ce-board-fe/.eslintignore
> +build/*
넵넵! 안그래도 한번 더 depth가 생겨서 이게 맞을라나.. 했는데! 맞는 말씀이에욤
반영하겠습니다! 🐶

2021-04-07 13:59 UTC, Derek-94 commented on hongik-ce-board-fe/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
기존 내용에 추가만 하면 되는거죠! 아예 replace는 아니겠지.. 싶어서요! 🤨

2021-04-08 08:38 UTC, lxxjn0 approved these changes
고쳐주셔서 감사합니다 :) 수고하셨어요 ㅎㅅㅎ

2021-04-09 00:20 UTC, merged